CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    price_yen bigint NOT NULL CHECK (price_yen >= 0),
    stock integer NOT NULL CHECK (stock >= 0)
);

INSERT INTO products (id, name, price_yen, stock) VALUES
    (1, '旬の野菜セット', 980, 10),
    (2, '北海道ミルク', 320, 20),
    (3, '焼きたて食パン', 480, 0)
ON CONFLICT (id) DO NOTHING;

SELECT setval(pg_get_serial_sequence('products', 'id'), (SELECT max(id) FROM products));
